addSbtPlugin("org.scalameta"     % "sbt-scalafmt"              % "2.3.2")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"             % "0.9.0")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"             % "1.6.1")
addSbtPlugin("com.github.cb372"  % "sbt-explicit-dependencies" % "0.2.13")
addSbtPlugin("de.heikoseeberger" % "sbt-header"                % "5.4.0")
addSbtPlugin("ch.epfl.scala"     % "sbt-bloop"                 % "1.3.5")
addSbtPlugin("com.geirsson"      % "sbt-ci-release"            % "1.5.2")
